version: '{build}'
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\gettext" )) {
        (new-object System.Net.WebClient).DownloadFile('https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.19.8.1-v1.14/gettext0.19.8.1-iconv1.14-shared-64.zip', 'C:\gettext-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\gettext-bin.zip", "C:\gettext")
      }
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk11
  - cmd: SET PATH=C:\gettext\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-Xmx2g
  - cmd: SET JAVA_OPTS=-Xmx2g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -B -DskipTests
test_script:
  - mvn clean install
cache:
- C:\gettext\
